repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.13.0-1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.0.0
          - eslint-plugin-prettier@3.1.3
          - prettier@2.0.5
        files: \.js$